module br {

    module com {

        module ajeferson {

            module corba {

                interface Agenda {
                    boolean isAlive();
                    boolean insert(in string name, in string phoneNumber);
                    boolean remove(in string name);
                };

                interface IdentityManager {
                    void identify(in string identity);
                };

            };

        };

    };

};