module br {

    module com {

        module ajeferson {

            module corba {

                interface Agenda {
                    boolean isAlive();
                    boolean insert(in string name, in string phoneNumber);
                    boolean remove(in string name);
                    boolean update(in string oldName, in string newName, in string newPhoneNumber);
                };

                interface IdentityManager {
                    void identify(in boolean isClient, in string identity, in boolean sync);
                };

            };

        };

    };

};