package br.com.ajeferson.corba;


/**
* br/com/ajeferson/corba/Agenda.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Segunda-feira, 30 de Abril de 2018 09h56min00s BRT
*/

public interface Agenda extends AgendaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Agenda
