package br.com.ajeferson.corba;

/**
* br/com/ajeferson/corba/AgendaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Segunda-feira, 30 de Abril de 2018 09h56min00s BRT
*/

public final class AgendaHolder implements org.omg.CORBA.portable.Streamable
{
  public br.com.ajeferson.corba.Agenda value = null;

  public AgendaHolder ()
  {
  }

  public AgendaHolder (br.com.ajeferson.corba.Agenda initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.com.ajeferson.corba.AgendaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.com.ajeferson.corba.AgendaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.com.ajeferson.corba.AgendaHelper.type ();
  }

}
