package br.com.ajeferson.corba;


/**
* br/com/ajeferson/corba/AgendaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Segunda-feira, 30 de Abril de 2018 09h56min00s BRT
*/

public interface AgendaOperations 
{
  boolean isAlive ();
  boolean insert (String name, String phoneNumber);
  boolean remove (String name);
  boolean update (String oldName, String newName, String newPhoneNumber);
} // interface AgendaOperations
