package br.com.ajeferson.corba;


/**
* br/com/ajeferson/corba/AgendaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Quarta-feira, 25 de Abril de 2018 10h40min02s BRT
*/

public interface AgendaOperations 
{
  boolean isAlive ();
  boolean insert (String name, String phoneNumber);
} // interface AgendaOperations
