package br.com.ajeferson.corba;


/**
* br/com/ajeferson/corba/Agenda.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Quarta-feira, 25 de Abril de 2018 10h40min02s BRT
*/

public interface Agenda extends AgendaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Agenda
