package br.com.ajeferson.corba;


/**
* br/com/ajeferson/corba/AgendaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Domingo, 29 de Abril de 2018 14h04min20s BRT
*/

abstract public class AgendaHelper
{
  private static String  _id = "IDL:br/com/ajeferson/corba/Agenda:1.0";

  public static void insert (org.omg.CORBA.Any a, br.com.ajeferson.corba.Agenda that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.com.ajeferson.corba.Agenda extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (br.com.ajeferson.corba.AgendaHelper.id (), "Agenda");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.com.ajeferson.corba.Agenda read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AgendaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.com.ajeferson.corba.Agenda value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static br.com.ajeferson.corba.Agenda narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.com.ajeferson.corba.Agenda)
      return (br.com.ajeferson.corba.Agenda)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.com.ajeferson.corba._AgendaStub stub = new br.com.ajeferson.corba._AgendaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static br.com.ajeferson.corba.Agenda unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.com.ajeferson.corba.Agenda)
      return (br.com.ajeferson.corba.Agenda)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.com.ajeferson.corba._AgendaStub stub = new br.com.ajeferson.corba._AgendaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
