package br.com.ajeferson.corba;


/**
* br/com/ajeferson/corba/IdentityManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Quinta-feira, 26 de Abril de 2018 17h26min30s BRT
*/

public interface IdentityManagerOperations 
{
  void identify (String identity, boolean sync);
} // interface IdentityManagerOperations
