package br.com.ajeferson.corba;


/**
* br/com/ajeferson/corba/IdentityManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Quinta-feira, 26 de Abril de 2018 02h37min32s BRT
*/

public interface IdentityManager extends IdentityManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IdentityManager
