package br.com.ajeferson.corba;


/**
* br/com/ajeferson/corba/IdentityManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Domingo, 29 de Abril de 2018 14h04min20s BRT
*/

public interface IdentityManager extends IdentityManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IdentityManager
