package br.com.ajeferson.corba;


/**
* br/com/ajeferson/corba/IdentityManagerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Quinta-feira, 26 de Abril de 2018 02h37min32s BRT
*/

public abstract class IdentityManagerPOA extends org.omg.PortableServer.Servant
 implements br.com.ajeferson.corba.IdentityManagerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("identify", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // br/com/ajeferson/corba/IdentityManager/identify
       {
         String identity = in.read_string ();
         this.identify (identity);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/com/ajeferson/corba/IdentityManager:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IdentityManager _this() 
  {
    return IdentityManagerHelper.narrow(
    super._this_object());
  }

  public IdentityManager _this(org.omg.CORBA.ORB orb) 
  {
    return IdentityManagerHelper.narrow(
    super._this_object(orb));
  }


} // class IdentityManagerPOA
